// Datos de la licencia

LISENSE_TYPE = 'Cluster';
LISENSE_STATUS = 'Active - Cluster';
LISENSE_MODEL = 'NETF-10GBPS-700';
LISENSE_CODE = 'NFW-7K9Q2M4XA1';
LISENSE_EXPIRES_AT = '2027-04-19';
LISENSE_DAYS = '372';
